
import React, { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabaseClient';
import { api } from '../../services/api';
import { Solution } from '../../types';
import { Plus, Edit, Trash2, X } from 'lucide-react';

const SolutionManager: React.FC = () => {
  const [solutions, setSolutions] = useState<Solution[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [formData, setFormData] = useState<Omit<Solution, 'id'>>({
    title: '',
    description: '',
    image: '',
    icon: '',
  });

  useEffect(() => {
    loadSolutions();
  }, []);

  const loadSolutions = async () => {
    const data = await api.getSolutions();
    setSolutions(data);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      if (editingId) {
        await api.admin.updateSolution(editingId, { ...formData, id: editingId });
      } else {
        // ID is usually generated by backend/db, but here we might need to generate or let DB handle
        // Our model has 'id' as text primary key. Let's assume user inputs it or we generate a random one if API expects it
        // The API call expects a full Solution object including ID if we are creating?
        // Let's check api.ts. createSolution takes 'Solution'.
        // We should generate a simple ID if not provided, or let user provide it.
        // For simplicity, generate a timestamp ID
        await api.admin.createSolution({ ...formData, id: Date.now().toString() });
      }
      setIsModalOpen(false);
      resetForm();
      loadSolutions();
    } catch (error) {
      console.error('Operation failed:', error);
      alert('操作失败，请重试');
    }
  };

  const handleDelete = async (id: string) => {
    if (window.confirm('确定要删除这个解决方案吗？')) {
      try {
        await api.admin.deleteSolution(id);
        loadSolutions();
      } catch (error) {
        console.error('Delete failed:', error);
        alert('删除失败');
      }
    }
  };

  const openEdit = (solution: Solution) => {
    setEditingId(solution.id);
    setFormData({
      title: solution.title || '',
      description: solution.description || '',
      image: solution.image || '',
      icon: solution.icon || '',
    });
    setIsModalOpen(true);
  };

  const resetForm = () => {
    setEditingId(null);
    setFormData({ title: '', description: '', image: '', icon: '' });
  };

  return (
    <div>
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold text-gray-800">解决方案管理</h1>
        <button
          onClick={() => { resetForm(); setIsModalOpen(true); }}
          className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition"
        >
          <Plus size={20} />
          <span>新增方案</span>
        </button>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        <table className="w-full text-left">
          <thead className="bg-gray-50 border-b border-gray-100">
            <tr>
              <th className="px-6 py-4 font-medium text-gray-500">标题</th>
              <th className="px-6 py-4 font-medium text-gray-500">描述</th>
              <th className="px-6 py-4 font-medium text-gray-500">图标</th>
              <th className="px-6 py-4 font-medium text-gray-500 text-right">操作</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {solutions.map((solution) => (
              <tr key={solution.id} className="hover:bg-gray-50">
                <td className="px-6 py-4 font-medium text-gray-900">{solution.title}</td>
                <td className="px-6 py-4 text-gray-600 max-w-md truncate">{solution.description}</td>
                <td className="px-6 py-4 text-gray-600">{solution.icon}</td>
                <td className="px-6 py-4 text-right space-x-2">
                  <button
                    onClick={() => openEdit(solution)}
                    className="text-blue-600 hover:text-blue-800 p-1"
                  >
                    <Edit size={18} />
                  </button>
                  <button
                    onClick={() => handleDelete(solution.id)}
                    className="text-red-600 hover:text-red-800 p-1"
                  >
                    <Trash2 size={18} />
                  </button>
                </td>
              </tr>
            ))}
            {solutions.length === 0 && (
              <tr>
                <td colSpan={4} className="px-6 py-8 text-center text-gray-500">
                  暂无数据
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {isModalOpen && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl w-full max-w-lg p-6 relative">
            <button
              onClick={() => setIsModalOpen(false)}
              className="absolute top-4 right-4 text-gray-400 hover:text-gray-600"
            >
              <X size={24} />
            </button>
            <h2 className="text-xl font-bold mb-6">{editingId ? '编辑方案' : '新增方案'}</h2>
            
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">标题</label>
                <input
                  type="text"
                  value={formData.title}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">描述</label>
                <textarea
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
                  rows={3}
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">图标名称 (Lucide Icon)</label>
                <input
                  type="text"
                  value={formData.icon}
                  onChange={(e) => setFormData({ ...formData, icon: e.target.value })}
                  className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
                  placeholder="e.g. Shield, Zap"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">图片</label>
                <ImageUpload
                  value={formData.image}
                  onChange={(url) => setFormData({ ...formData, image: url })}
                />
                {/* 隐藏的输入框用于表单验证 */}
                <input 
                  type="text" 
                  value={formData.image} 
                  required 
                  className="opacity-0 h-0 w-0 absolute"
                  onInvalid={(e) => (e.target as HTMLInputElement).setCustomValidity('请上传图片')}
                  onInput={(e) => (e.target as HTMLInputElement).setCustomValidity('')}
                />
              </div>
              
              <div className="flex justify-end gap-3 mt-6">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded-lg transition"
                >
                  取消
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
                >
                  保存
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default SolutionManager;
