-- Create exhibitions table
create table if not exists public.exhibitions (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  description text not null,
  start_date date not null,
  end_date date not null,
  location text not null,
  city text not null,
  tags text[] default '{}',
  image text not null,
  featured boolean default false,
  core_value text,
  highlights text[] default '{}',
  gallery_images text[] default '{}', -- Added gallery_images
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.exhibitions enable row level security;

-- Policies
create policy "Public exhibitions are viewable by everyone"
  on public.exhibitions for select
  using (true);

create policy "Authenticated users can insert exhibitions"
  on public.exhibitions for insert
  to authenticated
  with check (true);

create policy "Authenticated users can update exhibitions"
  on public.exhibitions for update
  to authenticated
  using (true);

create policy "Authenticated users can delete exhibitions"
  on public.exhibitions for delete
  to authenticated
  using (true);

-- Create exhibition_applications table
create table if not exists public.exhibition_applications (
  id bigint generated by default as identity primary key,
  exhibition_id uuid references public.exhibitions(id) on delete cascade,
  exhibition_title text not null,
  type text not null, -- 'ticket' | 'booth'
  name text not null,
  company text not null,
  phone text not null,
  email text,
  message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for applications
alter table public.exhibition_applications enable row level security;

-- Policies for applications
create policy "Public can insert applications"
  on public.exhibition_applications for insert
  to anon, authenticated
  with check (true);

create policy "Admins can view applications"
  on public.exhibition_applications for select
  to authenticated
  using (true);

-- Update for existing tables (if needed)
alter table public.exhibitions add column if not exists gallery_images text[] default '{}';
