from pydantic import BaseModel
from typing import Optional, List

class Solution(BaseModel):
    id: str
    title: str
    description: str
    image: str
    icon: str

class Product(BaseModel):
    id: str
    name: str
    category: str
    description: str
    image: str
    video: Optional[str] = None
    sort_order: Optional[int] = 0

class PartnerBenefit(BaseModel):
    id: Optional[int] = None  # Auto-generated by DB
    title: str
    description: str
    icon: str

class NewsItem(BaseModel):
    id: str
    title: str
    date: str
    category: str
    summary: str
    image: str
    source: Optional[str] = None
    author: Optional[str] = None

class PartnerApplication(BaseModel):
    name: str
    phone: str
    company: str
    target_city: str
    message: str

class ExhibitionApplication(BaseModel):
    id: Optional[int] = None
    exhibition_id: str
    exhibition_title: str
    type: str  # 'ticket' | 'booth'
    name: str
    company: str
    phone: str
    email: Optional[str] = None
    message: Optional[str] = None
    created_at: Optional[str] = None

class Exhibition(BaseModel):
    id: Optional[str] = None # UUID generated by DB
    title: str
    description: str
    start_date: str
    end_date: str
    location: str
    city: str
    tags: List[str] = []
    image: str
    featured: Optional[bool] = False
    core_value: Optional[str] = None
    highlights: List[str] = []
    gallery_images: List[str] = []
    created_at: Optional[str] = None

class LoginRequest(BaseModel):
    username: str
    password: str

class AdminUserCreate(BaseModel):
    username: str
    password: str
    role: str

class Token(BaseModel):
    access_token: str
    token_type: str
    username: str
    role: str

class Association(BaseModel):
    id: Optional[str] = None
    name: str
    type: str
    description: str
    content: Optional[str] = None
    join_info: Optional[str] = None
    logo: str
    contact_info: Optional[str] = None
    website: Optional[str] = None
    created_at: Optional[str] = None
