from pydantic import BaseModel
from typing import Optional

class Solution(BaseModel):
    id: str
    title: str
    description: str
    image: str
    icon: str

class Product(BaseModel):
    id: str
    name: str
    category: str
    description: str
    image: str
    video: Optional[str] = None
    sort_order: Optional[int] = 0

class PartnerBenefit(BaseModel):
    id: Optional[int] = None  # Auto-generated by DB
    title: str
    description: str
    icon: str

class NewsItem(BaseModel):
    id: str
    title: str
    date: str
    category: str
    summary: str
    image: str
    source: Optional[str] = None
    author: Optional[str] = None

class PartnerApplication(BaseModel):
    name: str
    phone: str
    company: str
    target_city: str
    message: str

class ExhibitionApplication(BaseModel):
    id: Optional[int] = None
    exhibition_id: str
    exhibition_title: str
    type: str  # 'ticket' | 'booth'
    name: str
    company: str
    phone: str
    email: Optional[str] = None
    message: Optional[str] = None
    created_at: Optional[str] = None

class LoginRequest(BaseModel):
    username: str
    password: str

class AdminUserCreate(BaseModel):
    username: str
    password: str
    role: str

class Token(BaseModel):
    access_token: str
    token_type: str
    username: str
    role: str
