from pydantic import BaseModel
from typing import Optional

class Solution(BaseModel):
    id: str
    title: str
    description: str
    image: str
    icon: str

class Product(BaseModel):
    id: str
    name: str
    category: str
    description: str
    image: str
    video: Optional[str] = None

class PartnerBenefit(BaseModel):
    id: Optional[int] = None  # Auto-generated by DB
    title: str
    description: str
    icon: str

class NewsItem(BaseModel):
    id: str
    title: str
    date: str
    category: str
    summary: str
    image: str

class PartnerApplication(BaseModel):
    name: str
    phone: str
    company: str
    target_city: str
    message: str
